### ISSUE TITLE
NullPointerException when receiving pending messages

### ISSUE THREAD

**Issue by CyB3RC0nN0R** [informatik-ag-ngl/envoy-client#167]
**Describe the bug**
A `NullPointerException` can be thrown by sending messages in a particular order.

**To Reproduce**
Steps to reproduce the behavior (prerequesites: server and two clients that are contacts of each other):
1. Start the server and client 1
2. Send a message to client 2
3. Stop both client and server
4. Start client 2
5. Send a message to client 1
6. Stop client 2, start the server and client 1
7. Open the chat with client 2
8. Start client 2

A stack trace should now appear in the log of client 2.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/14822954/86142631-aec22600-baf3-11ea-9a1f-f9519808f7af.png)
_Client 1 after executing steps 1 and 2_

![grafik](https://user-images.githubusercontent.com/14822954/86142725-ca2d3100-baf3-11ea-9fd1-052acc007147.png)
_Client 2 after executing steps 3 to 5_

`[2020-06-30 17:06:04] [INFO   ] [envoy.client.ui.Startup] Envoy starting...`
`[2020-06-30 17:06:05] [FINER  ] [envoy.client.net.Client] Attempting connection to server localhost:8080...`
`[2020-06-30 17:06:05] [FINE   ] [envoy.client.net.Client] Successfully established TCP connection to server`
`[2020-06-30 17:06:05] [FINE   ] [envoy.client.net.Receiver] Received User[id=2,name=Maxi,status=ONLINE,contacts=[User[id=1,name=Kai,status=ONLINE,contacts=[]]]]`
`[2020-06-30 17:06:05] [FINE   ] [envoy.client.net.Receiver] Received Message[id=0,sender=1,recipient=2,date=30.06.2020 17:03:44,status=SENT,text=Message 1,forwarded=false,hasAttachment=false]`
`[2020-06-30 17:06:05] [FINE   ] [envoy.client.data.Cache] Adding element Message[id=0,sender=1,recipient=2,date=30.06.2020 17:03:44,status=SENT,text=Message 1,forwarded=false,hasAttachment=false] to cache`
`[2020-06-30 17:06:05] [INFO   ] [envoy.client.net.Client] Handshake completed.`
`[2020-06-30 17:06:05] [FINER  ] [envoy.client.net.WriteProxy] Sending cachedMessage[id=200,sender=2,recipient=1,date=30.06.2020 17:04:31,status=WAITING,text=Message 2,forwarded=false,hasAttachment=false]`
`[2020-06-30 17:06:05] [FINE   ] [envoy.client.net.Client] Sending Message[id=200,sender=2,recipient=1,date=30.06.2020 17:04:31,status=WAITING,text=Message 2,forwarded=false,hasAttachment=false]`
`[2020-06-30 17:06:05] [FINE   ] [envoy.client.net.Receiver] Received MessageStatusChange[id=200,status=RECEIVED,date=2020-06-30T17:06:05.813789500]`
`[2020-06-30 17:06:05] [FINE   ] [envoy.client.net.Receiver] Received MessageStatusChange[id=200,status=READ,date=2020-06-30T17:06:05.816781800]`
`[2020-06-30 17:06:05] [SEVERE ] [envoy.client.net.Receiver] Error on receiver thread`
`java.lang.NullPointerException
	at envoy/envoy.client.ui.controller.ChatScene.lambda$5(ChatScene.java:118)
	at envoy.common@0.1-beta/envoy.event.EventBus.lambda$dispatch$0(EventBus.java:69)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1624)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:274)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1694)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at envoy.common@0.1-beta/envoy.event.EventBus.dispatch(EventBus.java:69)
	at envoy/envoy.client.net.MessageStatusChangeProcessor.accept(MessageStatusChangeProcessor.java:33)
	at envoy/envoy.client.net.MessageStatusChangeProcessor.accept(MessageStatusChangeProcessor.java:1)
	at envoy/envoy.client.net.Receiver.run(Receiver.java:75)`
_The full log of client 2 after step 8_

**Expected behavior**
No exception, however message 2 would still appear above message 1 on client 2:
![grafik](https://user-images.githubusercontent.com/14822954/86143650-feedb800-baf4-11ea-9293-e202835dc2da.png)

**Environment:**
- OS: Microsoft Windows
- Current development build of Envoy

**Comment by CyB3RC0nN0R** [comment]
Just tried it again with Java 14's helpful NullPointerExceptions and logged the following: `java.lang.NullPointerException: Cannot invoke "envoy.client.data.LocalDB.getMessage(long)" because "this.localDB" is null`
